# Site settings
name: cho young kwang
email: youri1005y@hanmail.net
url: https://choportfolio.netlify.app/
description: "A blog and a portfolio"
author: "조영광"
title: "조영광의BlogFolio"
permalink: ""
baseurl: ""

# social
github:
  username: Glory-m

twitter:
  username: ""
